# http://travis-ci.org/#!/RDFLib/FuXi
sudo: false
language: python
# whitelist
branches:
  only:
    - master

python:
    # - 2.5
    - 2.6
    - 2.7
    # - 3.2
    - 3.3
    - 3.4
    - "pypy"

install:
    # - if [[ $TRAVIS_PYTHON_VERSION == '2.5' ]]; then pip install --use-mirrors ordereddict; pip install --use-mirrors "simplejson"; pip install --use-mirrors "elementtree"; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --default-timeout 60 ordereddict; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install --default-timeout 60 -r requirements.py2.txt; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then pip install --default-timeout 60 -r requirements.py3.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --default-timeout 60 --allow-external isodate; pip install --default-timeout 60 --allow-external elementtree; fi
    - python --version
    - python setup.py install

before_script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then flake8 --exclude=tools,examples --exit-zero FuXi; fi

script:
    # Must run the tests in build/src so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version in build/src.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then nosetests; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then nosetests --where=./build/src; fi
# notifications:
#   irc:
#     channels: "irc.freenode.org#rdflib"
#     on_success: change
#     on_failure: change
